# Generated by Django 4.1.3 on 2022-12-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_todoitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
